apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  # 类型：NodePort（通过节点端口暴露，便于本地访问）
  type: NodePort
  
  # 选择器：选择app=api的Pod
  selector:
    app: api
  
  ports:
  - name: http
    protocol: TCP
    port: 8080        # Service端口
    targetPort: 8080  # Pod端口
    nodePort: 30080   # 节点端口（可选，范围30000-32767）
