apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
    version: v0.2
spec:
  # NodePort：允许从集群外部访问
  type: NodePort
  
  selector:
    app: api
  
  ports:
  - port: 8080          # Service 端口
    targetPort: 8080    # Pod 端口
    nodePort: 30080     # 节点端口（外部访问）
    name: http
    protocol: TCP
  
  # 会话亲和性（可选）
  # 如果需要会话保持，可以设置为 ClientIP
  sessionAffinity: None

