apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 基础配置
resources:
  - ../../base

# 环境标识
namePrefix: dev-

labels:
  - pairs:
      env: dev

# 资源补丁
patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
